# Run in docker-compose on master not in swarm, prometheus has some issues; https://github.com/prometheus/prometheus/issues/6943
version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  grafana:
    image: grafana/grafana:6.7.0
    user: "1001"
    restart: always
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    user: "1001"
    restart: always
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090




        

