global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'master-node'
    static_configs:
      - targets: ['10.0.0.1:9100']
  - job_name: 'slave1-node'
    static_configs:
      - targets: ['10.0.0.2:9100']
  - job_name: 'slave2-node'
    static_configs:
      - targets: ['10.0.0.3:9100']
  - job_name: 'swarm-master'
    static_configs:
      - targets: ['10.0.0.1:9323']

